[2023-02-10T09:39:15.386+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: my_first_dagV2.get_save_new_data scheduled__2023-01-29T00:00:00+00:00 [queued]>
[2023-02-10T09:39:15.402+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: my_first_dagV2.get_save_new_data scheduled__2023-01-29T00:00:00+00:00 [queued]>
[2023-02-10T09:39:15.402+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-02-10T09:39:15.402+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-02-10T09:39:15.402+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-02-10T09:39:15.421+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): get_save_new_data> on 2023-01-29 00:00:00+00:00
[2023-02-10T09:39:15.425+0000] {standard_task_runner.py:55} INFO - Started process 29659 to run task
[2023-02-10T09:39:15.428+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'my_first_dagV2', 'get_save_new_data', 'scheduled__2023-01-29T00:00:00+00:00', '--job-id', '64', '--raw', '--subdir', 'DAGS_FOLDER/dag1.py', '--cfg-path', '/tmp/tmpjhv7ubdo']
[2023-02-10T09:39:15.428+0000] {standard_task_runner.py:83} INFO - Job 64: Subtask get_save_new_data
[2023-02-10T09:39:15.534+0000] {task_command.py:388} INFO - Running <TaskInstance: my_first_dagV2.get_save_new_data scheduled__2023-01-29T00:00:00+00:00 [running]> on host 47e55e08a495
[2023-02-10T09:39:15.769+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_first_dagV2
AIRFLOW_CTX_TASK_ID=get_save_new_data
AIRFLOW_CTX_EXECUTION_DATE=2023-01-29T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-29T00:00:00+00:00
[2023-02-10T09:39:15.770+0000] {python.py:177} INFO - Done. Returned value was: 2
[2023-02-10T09:39:15.849+0000] {taskinstance.py:1323} INFO - Marking task as SUCCESS. dag_id=my_first_dagV2, task_id=get_save_new_data, execution_date=20230129T000000, start_date=20230210T093915, end_date=20230210T093915
[2023-02-10T09:39:15.925+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2023-02-10T09:39:15.951+0000] {taskinstance.py:2578} INFO - 1 downstream tasks scheduled from follow-on schedule check
