[2023-02-01T10:13:10.091+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: my_third_dagV1.fo manual__2023-02-01T10:13:09.339237+00:00 [queued]>
[2023-02-01T10:13:10.100+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: my_third_dagV1.fo manual__2023-02-01T10:13:09.339237+00:00 [queued]>
[2023-02-01T10:13:10.100+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-02-01T10:13:10.101+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-02-01T10:13:10.101+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-02-01T10:13:10.113+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): fo> on 2023-02-01 10:13:09.339237+00:00
[2023-02-01T10:13:10.118+0000] {standard_task_runner.py:55} INFO - Started process 1339 to run task
[2023-02-01T10:13:10.122+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'my_third_dagV1', 'fo', 'manual__2023-02-01T10:13:09.339237+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/dag3.py', '--cfg-path', '/tmp/tmpx01ckg8e']
[2023-02-01T10:13:10.123+0000] {standard_task_runner.py:83} INFO - Job 11: Subtask fo
[2023-02-01T10:13:10.193+0000] {task_command.py:388} INFO - Running <TaskInstance: my_third_dagV1.fo manual__2023-02-01T10:13:09.339237+00:00 [running]> on host 47e55e08a495
[2023-02-01T10:13:10.291+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_third_dagV1
AIRFLOW_CTX_TASK_ID=fo
AIRFLOW_CTX_EXECUTION_DATE=2023-02-01T10:13:09.339237+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-01T10:13:09.339237+00:00
[2023-02-01T10:13:12.101+0000] {logging_mixin.py:137} INFO - Empty DataFrame
Columns: []
Index: []
[2023-02-01T10:13:12.104+0000] {logging_mixin.py:137} INFO - Вы подключены к -  (2, '100005', 'NULL') 
[2023-02-01T10:13:12.104+0000] {logging_mixin.py:137} INFO - Соединение с PostgreSQL закрыто
[2023-02-01T10:13:12.104+0000] {python.py:177} INFO - Done. Returned value was: 2
[2023-02-01T10:13:12.146+0000] {taskinstance.py:1323} INFO - Marking task as SUCCESS. dag_id=my_third_dagV1, task_id=fo, execution_date=20230201T101309, start_date=20230201T101310, end_date=20230201T101312
[2023-02-01T10:13:12.198+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2023-02-01T10:13:12.215+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
