[2023-01-28T15:34:04.180+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: my_second_dagV5.save_new_data manual__2023-01-28T15:34:02.801314+00:00 [queued]>
[2023-01-28T15:34:04.187+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: my_second_dagV5.save_new_data manual__2023-01-28T15:34:02.801314+00:00 [queued]>
[2023-01-28T15:34:04.187+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-01-28T15:34:04.187+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-01-28T15:34:04.187+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-01-28T15:34:04.200+0000] {taskinstance.py:1300} INFO - Executing <Task(PostgresOperator): save_new_data> on 2023-01-28 15:34:02.801314+00:00
[2023-01-28T15:34:04.205+0000] {standard_task_runner.py:55} INFO - Started process 23751 to run task
[2023-01-28T15:34:04.208+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'my_second_dagV5', 'save_new_data', 'manual__2023-01-28T15:34:02.801314+00:00', '--job-id', '56', '--raw', '--subdir', 'DAGS_FOLDER/dag2.py', '--cfg-path', '/tmp/tmpflasmwp7']
[2023-01-28T15:34:04.208+0000] {standard_task_runner.py:83} INFO - Job 56: Subtask save_new_data
[2023-01-28T15:34:04.354+0000] {task_command.py:388} INFO - Running <TaskInstance: my_second_dagV5.save_new_data manual__2023-01-28T15:34:02.801314+00:00 [running]> on host 9763ece73850
[2023-01-28T15:34:04.424+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_second_dagV5
AIRFLOW_CTX_TASK_ID=save_new_data
AIRFLOW_CTX_EXECUTION_DATE=2023-01-28T15:34:02.801314+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-28T15:34:02.801314+00:00
[2023-01-28T15:34:04.424+0000] {sql.py:254} INFO - Executing: 
            CREATE TABLE IF NOT EXISTS dag_runs (
                dt date, 
                dag_id character varying,
                PRIMARY KEY (dt, dag_id)
            )
          
[2023-01-28T15:34:04.431+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-01-28T15:34:04.607+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-01-28T15:34:04.610+0000] {sql.py:375} INFO - Running statement: 
            CREATE TABLE IF NOT EXISTS dag_runs (
                dt date, 
                dag_id character varying,
                PRIMARY KEY (dt, dag_id)
            )
          , parameters: None
[2023-01-28T15:34:04.618+0000] {taskinstance.py:1323} INFO - Marking task as SUCCESS. dag_id=my_second_dagV5, task_id=save_new_data, execution_date=20230128T153402, start_date=20230128T153404, end_date=20230128T153404
[2023-01-28T15:34:04.664+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2023-01-28T15:34:04.705+0000] {taskinstance.py:2578} INFO - 1 downstream tasks scheduled from follow-on schedule check
